import Head from 'next/head'

import dynamic from 'next/dynamic'

const OpenblocksAppView = dynamic(() => import('openblocks-sdk').then((mod) => mod.OpenblocksAppView), {
  loading: () => 'Loading...',
  ssr: false,
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <OpenblocksAppView appId='6374b8dbc23a1103804cc23e'/>
    </>
  )
}
